default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: monologue_app_development

test:
  <<: *default
  database: monologue_app_test

production:
  <<: *default
  database: monologue_app_production
  username: monologue_app
  password: <%= ENV['MONOLOGUE_APP_DATABASE_PASSWORD'] %>
